[platformio]
default_envs = esp32dev

[env]
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    WiFi
    https://github.com/bblanchon/ArduinoJson.git#7.x
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.filesystem = littlefs
build_flags =
    -D ESP32
    -D BOARD_ESP32
    -D PIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH
    -D CONFIG_ASYNC_TCP_USE_WDT=0
    -D CORE_DEBUG_LEVEL=0
    -O3
    -Wall
monitor_filters = esp32_exception_decoder
upload_protocol = esptool
