[platformio]
default_envs = esp-wrover-kit

[env]
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
    knolleary/PubSubClient @ ^2.8

[env:esp-wrover-kit]
platform = espressif32
board = esp-wrover-kit
framework = arduino
board_build.filesystem = spiffs
build_flags =
    -D ESP32
    -D BOARD_ESP32
    ${env.build_flags}
    -D ESP32
    -D PIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH
    -O3
    -Wall
    -D SPIFFS_BASE_PATH="\"/\""
